### ISSUE TITLE
silkscreen for analog#3 should be temp#3

### ISSUE THREAD

**Issue by rusefi** [rusefi/hw_microRusEfi#100]
analog#3 is temp#3 since this group (channels 1 to 4) has 2.7 pull-up on default BOM

**Comment by jharvey** [comment]
I updated the analog net names, and PCB silk for the analog. Looks like the same should happen for the TLE8888 outputs. Those are messy and names could be more consistent.

**Comment by rusefi** [comment]
pin 24 is now AT3
pin 31 is now AV3
