### ISSUE TITLE
c3 c11 wrong part number? 06031A470JAT2A is not 4.7nF

### ISSUE THREAD

**Issue by rusefi** [rusefi/hw_microRusEfi#104]
https://github.com/rusefi/hw_microRusEfi/blob/master/microRusEfi.csv says "C11 C3 ,2,4.7nF,Capacitor_SMD:C_0603_1608Metric,~,AVX,06031A470JAT2A"

https://rusefi.com/docs/ibom/microRusEfi_latest.html says "C3, C11 | 06031A470JAT2A | 4.7nF" 

mouser says that 06031A470JAT2A is  47pF 

 4.7nF is 4700pF?

Something not right?

**Comment by jharvey** [comment]
I believe this has been completed and can be marked done.
