### ISSUE TITLE
reset button

### ISSUE THREAD

**Issue by rusefi** [rusefi/hw_microRusEfi#105]
in my day to day workflow I need reset button - sometimes DFU fails, sometimes USB needs to be re-enumerated due to Windows7 drivers bug - in the end of the day it's annoying to remove all three sources of power for reset

would save me much time if we have an optional reset button.

can we please route the button to between flash storage ship and GND 5v test pads? maybe lower test bads a bit if needed or move test pads silkscreen?

my understanding is that reset push button would need to bring pin #14 to GND

**Comment by jharvey** [comment]
Is this what you mean?
