### ISSUE TITLE
[0.3.1] D1 is the hottest part of MRE - just add vias for [0.3.1]?

### ISSUE THREAD

**Issue by rusefi** [rusefi/hw_microRusEfi#106]
Without the rear panel D1 is 70C

With rear panel it's still 50C

@jharvey says
P-mosfet?
faster diode?
thermal via?

**Comment by DonaldBecker** [comment]
It's in continuous conduction mode, so a faster diode won't help.

Any heat eliminated by using a protection MOSFET will just be moved to the V6V MOSFET.  (Which should already be burning 10x the power of the diode.)

The answer seems to be adding thermal vias and conducting heat to the case, or using a buck/buck-boost supply.

**Comment by rusefi** [comment]
A lot of progress was made on 0.4.x
