### ISSUE TITLE
[stretch goal] Convert digital inputs to analog inputs

### ISSUE THREAD

**Issue by mck1117** [rusefi/hw_microRusEfi#11]
More analog inputs would be great.  If we can find the board area/routing magic, it would be great to have full analog inputs instead of the 4x digital inputs.

**Comment by 960** [comment]
This is done in latest revision.

**Comment by mck1117** [comment]
Awesome! So we now have ~15 analog inputs?

**Comment by 960** [comment]
Yes, 14 + Vbat to be correct

**Comment by mck1117** [comment]
Excellent!
