### ISSUE TITLE
[0.4.7] VRef drama continues

### ISSUE THREAD

**Issue by rusefi** [rusefi/hw_microRusEfi#127]
JP1 to vref with 6.8K/10K divider is not happy :( vref point measures 2.48 not expected 2.99

@mck1117 says "0.5v thru a 6.8k resistor is 75uA

Typical draw on vref during ADC conversion is 300uA"

**Comment by rusefi** [comment]
0.4.7 has a minor mistake that the wrong side of that jumper is the default

it should be cut & soldered/jumpered to the "vdda" side

![image](https://user-images.githubusercontent.com/7377949/77007101-ff918280-6939-11ea-8cbb-62e41da4cf8d.png)

**Comment by rusefi** [comment]
@mck1117 says "I'd just toss it 
Just tie vref to avdd, no jumper"

**Comment by jharvey** [comment]
This is obsolete, suggest closing this issue
