### ISSUE TITLE
Functional test board PCB - with pigtail

### ISSUE THREAD

**Issue by rusefi** [rusefi/hw_microRusEfi#137]
it would be nice to replace hand-made test board with a proper PCB

0) the board should accept wires from 48 pin pigtail
1) the board would need a few LEDs to indicate 5v & 12v
2) the board should have LEDs to test all MRE outputs
3) the board should have buttons to test CAM inputs
4) the board should have some resistor dividers to test analog inputs

**Comment by rusefi** [comment]
Current state of this (shown one of two boards, complete test jig takes two boards at the moment, each board with 24 wires)

![mre_test_board1](https://user-images.githubusercontent.com/7377949/75416030-48d25180-58fb-11ea-8307-649d50e33fb5.jpg)

**Comment by rusefi** [comment]
See also #140

**Comment by rusefillc** [comment]
done
