### ISSUE TITLE
Functional test board PCB - without pigtail

### ISSUE THREAD

**Issue by rusefi** [rusefi/hw_microRusEfi#140]
1) 2x12v red LEDs

2) 2x5v LEDs

3) a fuse (see Frankenso part - I have those)

4) x8 low side LEDs

5) x6 high-side LEDs

6) 5.5mm barrel jack is what I use for those

**Comment by rusefi** [comment]
Need to find larger pogo pins - current pins are smaller than connector holes on microRusEfi

![need_larger_pojo_pins](https://user-images.githubusercontent.com/7377949/76154117-e15b9500-60a4-11ea-99af-25472cc879c4.jpg)

**Comment by rusefi** [comment]
LED board would use same footprint as real MRE board

the idea is for LED board to use #6 bolts in order to sit on the board being test - #6 bolts match the mounting holes perfectly

MRE would stimulate itself and output low-side injector and high-side ignition signals. LED board should display those outputs using LEDs

![test_board_on_top_subject_board_below](https://user-images.githubusercontent.com/7377949/76154131-22ec4000-60a5-11ea-9f00-644335bba1b5.jpg)

![test_board_with_hardware](https://user-images.githubusercontent.com/7377949/76154133-22ec4000-60a5-11ea-9e40-47e5c3cd1f9f.jpg)

**Comment by rusefi** [comment]
P100-E2 pogo pins seem relevant

**Comment by rusefi** [comment]
There is a plan to make progress at https://github.com/rusefi/hw_microRusEfi/tree/master/test_fixture

@jharvey is on the job!

**Comment by rusefillc** [comment]
done
