### ISSUE TITLE
pads for SMD coin battery on the back

### ISSUE THREAD

**Issue by rusefi** [rusefi/hw_microRusEfi#142]
Shall we allow soldering of CR2016-MFR-SM on the back?

CR2016-MFR-SM costs $1 from Mouser

Better ideas?

**Comment by rusefi** [comment]
RecaroRacer will try 2 pin angled connector Molex 53048-0210 since there seem to be wired cr2016 on eBay

**Comment by jharvey** [comment]
Is the 2 pin connector OK? The 2 pin connector has been added, so this can probably be closed.

**Comment by jharvey** [comment]
2 pin connector was decided upon, this can be closed.
