### ISSUE TITLE
Do we really want to sense vBatt on the main relay pin?

### ISSUE THREAD

**Issue by mck1117** [rusefi/hw_microRusEfi#146]
Currently we sense from the main relay pin (pin 1), which is *technically* optional to use.  That can cause user confusion for the case of "I wired power and ground, why doesn't my ECU show voltage?"

**Comment by rusefi** [comment]
Let's abort? looks like there are benefits to this setup as well.

at the moment we only invoke tle8888 initialization once we get +12 from MR.
