### ISSUE TITLE
Schematic and PCB inconsistency

### ISSUE THREAD

**Issue by dron0gus** [rusefi/hw_microRusEfi#149]
![Screenshot from 2020-04-08 20-36-33](https://user-images.githubusercontent.com/28624689/78815414-ea5bc100-79d8-11ea-9d67-bbb80a73f172.png)
PCB has C47, C46, C16, C45 that do not present on schematic.
Do we need these caps? According PCB these are 6.8nF caps on AV6..AV9 inputs.

**Comment by rusefi** [comment]
@jharvey ?

**Comment by rusefi** [comment]
Looks like this is related to #150
