### ISSUE TITLE
Drive additional outputs from TLE8888

### ISSUE THREAD

**Issue by dron0gus** [rusefi/hw_microRusEfi#151]
U9, U10 can be connected to TLE8888 push-pull stages OUT8..13.
Pros and cons:
+TLE8888 is closet to U9 and U10
+free 4xSTM32 pins
+TLE8888 can do diagnostic on this outputs (using DFB)
+cheaper 5V MOSFETs can be used.
-no one try it before

**Comment by jharvey** [comment]
Added in R0.5.0 this can be closed.
