### ISSUE TITLE
External +5v power source

### ISSUE THREAD

**Issue by rusefi** [rusefi/hw_microRusEfi#154]
At the moment we have USB on the 48 pin but we cannot feed +5v into MRE via the connector

this is forcing users to power from +12v which is not safe for firmware flashing

is there any chance to allow external +5v into MRE?

**Comment by dron0gus** [comment]
Use one of analog inputs to feed USB 5V? Through diode to avoid influence during normal operation? Diode can also be used as jumper - it can be removed if user wants analog functionality only.

**Comment by rusefi** [comment]
how about AV10?
1. i like that it's on the edge pin on the connector
2. I like "10" as in "often not used"

**Comment by rusefi** [comment]
we have this on 0.5.0

so far I believe this was NOT tested

**Comment by rusefi** [comment]
looks like this works
