### ISSUE TITLE
vias for some of J2 pads

### ISSUE THREAD

**Issue by rusefi** [rusefi/hw_microRusEfi#156]
Just in case can we have vias for between 1 and 3 pads of J2?

the most interesting pad to have a via on would be J2 SWO
we can also can potentially benefit from SWDIO and SCK as a via

![image](https://user-images.githubusercontent.com/7377949/80320194-f28e6b80-87e2-11ea-9ace-808c97ff09b1.png)

**Comment by jharvey** [comment]
This was done in R0.5.0, this can be closed.
