### ISSUE TITLE
test fixture: why are there two sets of LED for main relay?

### ISSUE THREAD

**Issue by mck1117** [rusefi/hw_microRusEfi#162]
![image](https://user-images.githubusercontent.com/568254/81874262-63978800-9532-11ea-853f-d0245eaee4e7.png)

Main relay is a lowside output.  So what are the left set doing (R11/D21/D20)?

**Comment by rusefi** [comment]
@mck1117 D22 is not MR, D22 is aux low side on AV10

but MR has to become low side that's for sure

**Comment by mck1117** [comment]
oh, oops, misread which wire that was.  But yes, the point stands, MR should be low side like the others over on the right.

**Comment by jharvey** [comment]
This was updated on R0.1 release. Just noticed the issue tracker now. Sorry no git link to specific rev that fixed this.
