### ISSUE TITLE
VR input: R9 and R15 useful or not?

### ISSUE THREAD

**Issue by rusefi** [rusefi/hw_microRusEfi#171]
R9=R15 DNP = more sensitive

both R9 and R15 in place = lower signal level, possibly necessary for extremely hot sensors

Matthew Kennedy  says: 
I have no data to support that they are required since the tle8888 has internal clamp diodes to prevent overvoltage
so I might even go so far as to say that we should just remove them
the tle8888 datasheet application diagrams don't mention having a resistor there
I have no idea why we have them honestly

**Comment by jharvey** [comment]
Perhaps change for TVS diodes, that kick in when above a specific voltage, then they don't attenuate when low RPM. Very similar to the 8888's internal TVS. The "VR Sensor Interface Input Clamping Voltage" is as low as 2V, and "VR Sensor Interface Input Clamping Current" is a max of 50mA. I see 3.3V TVS are available from JLC, perhaps we can find a lower voltage diode. https://datasheet.lcsc.com/szlcsc/ProTek-Devices-PSD03-LF-T7_C139297.pdf

**Comment by rusefi** [comment]
let's just DNP R9 and R15?

**Comment by rusefi** [comment]
it was decided not to populate R9 and R15

see also #178

**Comment by rusefillc** [comment]
0.5.2 was fabricated without R15 but with R9

i think that's similar to the R2 issue, we need to DNP R9 a bit more :) @jharvey 

![IMG_20200727_124327](https://user-images.githubusercontent.com/48498823/88568401-f6f73a00-d006-11ea-9c6e-9b0605f77c87.jpg)

**Comment by Qwerty-OFF** [comment]
![image](https://user-images.githubusercontent.com/4116383/164896215-8acfba48-3fda-4984-8d96-497e1cadc6d2.png)
