### ISSUE TITLE
Mark R2 DNP

### ISSUE THREAD

**Issue by rusefi** [rusefi/hw_microRusEfi#175]
R2 watchdog connect is preventing stm32 from start unless we have tle8888 powered via +12v

let's DNP R2 for now

**Comment by rusefi** [comment]
@jharvey could this be closed?

**Comment by jharvey** [comment]
Hmmmm, I see 
![image](https://user-images.githubusercontent.com/43058/88165541-d92f6c80-cbe3-11ea-8f4c-804b8b032210.png)
However the BOM comes out like this. 
![image](https://user-images.githubusercontent.com/43058/88165591-ef3d2d00-cbe3-11ea-9227-d48178e5a742.png)

**Comment by reportingsjr** [comment]
This is an issue with your BOM script, not with KiCad.
If you look at the BOM script it is grouping components only by footprint type and value, hence why it is grouping your DNP resistor in there.

Change the R2 value to DNP and I bet it will separate it out.

I do wish KiCad had some other default fields like DNP so scripts could be more consistent on this!

**Comment by jharvey** [comment]
Made "0R" into "0R DNP" This now should work long term.

**Comment by MHTSOSVOODOO** [comment]
We could replace R2 with a diode with the cathode pointing towards the reset button. This way you can still reset TLE8888 when you press the button but it can't pull the reset line to ground when 12V is missing. I tried it and it seems to work.
