### ISSUE TITLE
[test fixture] crank testing: hall? VR?

### ISSUE THREAD

**Issue by rusefi** [rusefi/hw_microRusEfi#177]
for hall crank sensor with a pull-up test button schematics should be just a button to GND without resistors.

open question if current schematics works to test VR

![20200613_191111 crank hall](https://user-images.githubusercontent.com/7377949/84580966-5af0d680-adaa-11ea-8155-f7420c713893.jpg)

**Comment by jharvey** [comment]
Please review did I do this how we prefer?
