### ISSUE TITLE
[test fixture] [IMPORTANT] J2 is flipped

### ISSUE THREAD

**Issue by rusefi** [rusefi/hw_microRusEfi#179]
![image](https://user-images.githubusercontent.com/7377949/85080519-63c11e00-b197-11ea-80b2-d395928ecb21.png)

GND and 3v

5v and etc - a lot of stuff is flipped

**Comment by rusefi** [comment]
@stefanst FYI do NOT solder J2 bottom header on test fixture

@jharvey Houston we have a problem

**Comment by jharvey** [comment]
Can I get a confirmation that this is completed? I think I already completed this one.

**Comment by rusefillc** [comment]
Looks resolved, closing
