### ISSUE TITLE
pin contention - TLE8888 + CS + BT

### ISSUE THREAD

**Issue by rusefi** [rusefi/hw_microRusEfi#180]
TL,DR: do we have ANOTHER set of UART pins exposed on MRE not PC10&PC11?

How do we get MRE to
1) obviously keep using SPI for TLE8888
2) have different SPI for SD card
3) and also have UART for Bluetooth?

TLE8888 uses TBD pins which conveniently could be multiplexed to SPI1 or SPI3
SD card ideally should be running on a different SPI to reduce contention. We have complete SPI exposed which uses PC10&PC11

so if PC10 and PC11 is used by SPI for SD, do we have another pair of pins exposed on all the little random vias? if not, what would be the minimal HW change to have uart exposed without sharing pins with SPI?

**Comment by rusefi** [comment]
@ksmola since you did UART recently poke :)

**Comment by rusefi** [comment]
see table on the bottom of https://github.com/rusefi/rusefi/wiki/Hardware_microRusEfi_wiring

**Comment by rusefi** [comment]
![image](https://user-images.githubusercontent.com/7377949/85612782-2f31e400-b627-11ea-9b48-703c16c8482e.png)

**Comment by rusefi** [comment]
![image](https://user-images.githubusercontent.com/7377949/85612890-4b358580-b627-11ea-96fc-1f7c01cff302.png)

how about PB10 & PB11 which are used for SPI Flash right now? Does SPI use them simply as GPIO?

**Comment by jharvey** [comment]
I'm not following the request. Is this correct?
PB10 on SD card --> PE0
PB11 on SD card --> PC13
Then we want 
PB10 to a via for UART via soldered wire
PB11 to a via for UART via soldered wire

**Comment by rusefi** [comment]
The request:
before the change PB10 PB11 were routed to SPI Flash (not SD card)
PE0 PC13 were available to outside world via VIAs

The request:
swap pin usage. use PE0 PC13 to control SPI Flash
make PB10 PB11 available to outside world via VIAs

@jharvey

**Comment by jharvey** [comment]
My key concern is if PE0 or PC13 should be connected to the flash traced called HOLD? I have committed a draft copy. Did I get the correct signal to the correct pin? If they are flipped does that matter? Is the PCB as it's drawn now correct and ready for MFG files?

**Comment by rusefi** [comment]
Does not matter which one is which, it's GPIO so full programmatic control

**Comment by jharvey** [comment]
Thanks for the verification. This is routed, so we can close it.

**Comment by rusefi** [comment]
Before the change, 0.5.1 and older

![image](https://user-images.githubusercontent.com/7377949/87486652-bc0a0500-c609-11ea-868d-5fec6876a7ae.png)
