### ISSUE TITLE
[0.5.2] D41 orientation seems wrong in 

### ISSUE THREAD

**Issue by rusefi** [rusefi/hw_microRusEfi#183]
![placement_0 5 0 corrected](https://user-images.githubusercontent.com/7377949/87161014-e8ccbe00-c291-11ea-9e7c-dfbaa2fbf865.png)

![placement_0 5 0 corrections](https://user-images.githubusercontent.com/7377949/87161017-e8ccbe00-c291-11ea-9abe-bfd07163d938.png)

![placement_0 5 0 original](https://user-images.githubusercontent.com/7377949/87161018-e9655480-c291-11ea-8803-921a835b5020.png)

**Comment by jharvey** [comment]
How do we make the rotation script into a submodule? I think the issue is that we did not update the multiple projects to have the same specified rotation file.

**Comment by rusefillc** [comment]
I am confused. I've rotated D41 in placement file and submitted a new order, and it's STILL rotated?!


[micro_rusEFI_JLC-CPL_R0.5.2_from_order.csv.txt]
(https://github.com/rusefi/hw_microRusEfi/files/4977757/micro_rusEFI_JLC-CPL_R0.5.2_from_order.csv.txt)

![Produce_DanZhi SMT_Original_Snapshot Top 2582135A_Y47 SMT020061046764](https://user-images.githubusercontent.com/48498823/88481408-60088000-cf29-11ea-9e6c-e9b754fc67ec.png)

![Produce_DanZhi SMT_Original_Snapshot Top 2582135A_Y53 SMT020072660732](https://user-images.githubusercontent.com/48498823/88481409-61d24380-cf29-11ea-80cd-db13f14e31a2.png)

**Comment by jharvey** [comment]
Rotation updated, closed.

**Comment by rusefillc** [comment]
@jharvey D41 history
```
./Archived/rusEFI-Micro_R0.4.7-cpl.csv:D41,76.835000mm,-98.425000mm,Top,90
./0.4.8/rusEFI-Micro_R0.4.8-cpl.csv:D41,76.835000mm,-98.425000mm,Top,90
./0.5.0/rusEFI-Micro_R0.5.0_JLC_cpl.csv:D41,76.835000mm,-98.425000mm,Top,90
./R0.5.1/microRusEFI_R0.5.1_JLC-CPL.csv:D41,76.835000mm,-98.425000mm,Top,270
./R0.5.2/micro_rusEFI_JLC-CPL_R0.5.2.csv:D41,76.835000mm,-98.425000mm,Top,90
./R0.5.3/micro_rusEFI_R0.5.3_JLC_CPL.csv:D41,SM15T33C,76.835000,-98.425000,270.000000,top

```
