### ISSUE TITLE
Resistors R14, R23, R25 and R27 are wrong size in BOM - those are 2.7K pull ups on temperature sensor inputs

### ISSUE THREAD

**Issue by MHTSOSVOODOO** [rusefi/hw_microRusEfi#184]
Resistors R14/R23 and R25/R27 are 0603 in BOM and 0402 in board and on JLC assembled boards one or both sides of the resistors are shorted. 
![IMG_20200715_111424](https://user-images.githubusercontent.com/25746610/87561470-6f83ff80-c6c5-11ea-8bb0-5689163bf111.jpg)

**Comment by rusefi** [comment]
@jharvey what is the risk here? the v8 engine John has this board on the way to him

**Comment by jharvey** [comment]
BOMs are updated. We can close now.

**Comment by jharvey** [comment]
To many extended parts, need more basic parts 
![image](https://user-images.githubusercontent.com/43058/89708739-a73e3a00-d947-11ea-8aa0-7ebfadf640ec.png)

**Comment by jharvey** [comment]
Updated footprints to 0603, moved traces now closed again.
