### ISSUE TITLE
Diff of microRusEFI with SD card

### ISSUE THREAD

**Issue by rusefillc** [rusefi/hw_microRusEfi#214]
Looking to have a diff between https://github.com/rusefi/hw_microRusEfi master and https://github.com/rusefi/hw_microRusEfi/pull/211

**Comment by rusefillc** [comment]
@chuckwagoncomputing any chance you could help?

@Qwerty-OFF FYI

**Comment by chuckwagoncomputing** [comment]
Here's your diff. This is a diff to the point from which @JRDMcLAREN made his fork, not from the current master.

[diff.tar.gz](https://github.com/rusefi/hw_microRusEfi/files/8401127/diff.tar.gz)

**Comment by JRDMcLAREN** [comment]
I have some unpopulated PCBs. Can send it to somebody, if it helps.

**Comment by rusefillc** [comment]
@Qwerty-OFF  - un-compress https://github.com/rusefi/hw_microRusEfi/issues/214#issuecomment-1086379574 folder  and open web index.html in browser
