### ISSUE TITLE
non-JLCPCB Fab options

### ISSUE THREAD

**Issue by rusefillc** [rusefi/hw_microRusEfi#216]
1. The SM15T33CA on D41, it's out of stock, could we order the SM15T33CAY?
2. The IPD30N06S2L23ATMA3 on Q1, it's out of stock, the price is quite high on market, do you have an alternative part to recommend?

**Comment by rusefillc** [comment]
@Qwerty-OFF need your help

@jharvey :) do you remember about MRE? because MRE remembers about you.

**Comment by rusefillc** [comment]
2. IRLR2905TRPBF
JLCPCB Part C3010
TO-252-2
55V 42A 110W 27mΩ@10V,25A 2V@250μA N Channel TO-252-2(DPAK) MOSFETs ROHS

**Comment by Qwerty-OFF** [comment]
1. Yes

**Comment by rusefillc** [comment]
2. what about [IRLR2905ZTRPBF](https://octopart.com/irlr2905ztrpbf-infineon-65875016?r=sp) or [AUIRLR2905](https://octopart.com/auirlr2905-infineon-71801451?r=sp) or AUIRLR2905Z?

**Comment by rusefillc** [comment]
2. @mck1117 says AUIRLR2905 looks like closes thing to IRLR2905TRPBF
Z options are probably fine as well

**Comment by rusefillc** [comment]
jlcpbc has Z option C68209

**Comment by Qwerty-OFF** [comment]
Lower resisance (good), higher gate threshold (non-critical)
IRLR2905TRPBF:
![image](https://user-images.githubusercontent.com/4116383/162580051-78db22c7-c277-4ed3-99a3-c418f1231999.png)
IRLR2905ZTRPBF:
![image](https://user-images.githubusercontent.com/4116383/162580059-e2840b0d-e033-4414-b68a-8b4db39e3c94.png)
Other characteristics are similar, better, or not important to us
