### ISSUE TITLE
VR area silk outline

### ISSUE THREAD

**Issue by rusefillc** [rusefi/hw_microRusEfi#223]
We have a very nice Hall area outline

![image](https://user-images.githubusercontent.com/48498823/164280302-b79e03cf-e37d-4d93-9387-5c81bc1ba844.png)

can we please have something simi for VR which unfortunately is not a continues zone?

```
C12, R8
C35 R15
```

**Comment by Qwerty-OFF** [comment]
Maybe R9, not R8?
![image](https://user-images.githubusercontent.com/4116383/164896644-e61707cb-9770-4b03-bfa4-7da806884218.png)

**Comment by rusefillc** [comment]
Yes R9
