### ISSUE TITLE
ST-Link header and USB are too close to each other

### ISSUE THREAD

**Issue by rusefi** [rusefi/hw_microRusEfi#24]
@960 I believe ST-Link header and USB are too close to each other - as is they would not allow to be used simultaneously. Need to move 2mm further apart

here are the details:
eBay st-link connector width 20.4mm

random white micro USB cable width 12mm

st-link header and USB centers should be 32.4/2 = 16.2mm apart

currently st-link center line X=47

currently USB center line X=61.5

this is only 14.5mm apart

**Comment by 960** [comment]
In my current pcb file, they measure 16,5mm CC
