### ISSUE TITLE
Molex 48 pin silkscreen on the back

### ISSUE THREAD

**Issue by rusefi** [rusefi/hw_microRusEfi#25]
Can we please add some silkcreen on the back of the PCB for the connector?

definitely need some pin number reference at least for some pins otherwise we are blind

maybe even call out GND and 12v. 5v also?

**Comment by rusefi** [comment]
@960 what do you think?

**Comment by 960** [comment]
I think we need to make something like this
<img width="960" alt="1ES8DGu0qA" src="https://user-images.githubusercontent.com/9406140/58444368-2acf8a80-80f8-11e9-9f9b-ecc8e78452ee.png">

**Comment by rusefi** [comment]
Both :) We will have picture in the documentation but still some silkscreen would help

**Comment by 960** [comment]
Can we make help files work in TS?

**Comment by rusefi** [comment]
Not sure what you mean.

**Comment by rusefi** [comment]
We have progress :)

**Comment by rusefi** [comment]
![VirtualBoxVM_uRBtoLYVk4](https://user-images.githubusercontent.com/7377949/58555269-02728980-81e7-11e9-98f8-6e242921a7d2.png)

**Comment by rusefi** [comment]
This is good enough at the moment but in my opinion more could be added. Adding more silkscreen to the connector is a great cost/benefit ration in my opinion.

Lowering the priority but keeping open for now.

**Comment by rusefi** [comment]
looks great!
