### ISSUE TITLE
SPI flash

### ISSUE THREAD

**Issue by rusefi** [rusefi/hw_microRusEfi#26]
we seem to have space and pins

I believe SPI flash would be useful to record logs. 

SOIC-8 W25Q64JVSSIQ costs only $1 and gives us 8MB of logs - bad choice, too small

**Comment by rusefi** [comment]
MT29F2G01ABAGDSF-IT:G TR is 2G for $3 with SPI but I have no idea if that would work for in terms of custom SPI protocol. Just a normal SD card would be soooooo much nicer

**Comment by 960** [comment]
This is added, and can be closed

**Comment by rusefi** [comment]
@mck1117 reminds us that we like W25N01GVSFIT

**Comment by rusefi** [comment]
or was it MT29F1G01ABAFDSF-AAT:F TR?
or was it MT29F2G01ABAGDSF-IT:G?

**Comment by rusefi** [comment]
@mck1117 says
Our flash chip adheres to a JEDEC standard called JESD216

which chibios has a driver for!
