### ISSUE TITLE
Expose some unused stm32 pins

### ISSUE THREAD

**Issue by rusefi** [rusefi/hw_microRusEfi#29]
If we have space it would be nice to expose 4-10 pins using smd headers. Does not have to be one header, if it's easier to use a few 2x2 headers it could be a few 2x2 headers.

**Comment by jharvey** [comment]
Some STM32 and 8888 pads are now exposed as test points.

**Comment by rusefi** [comment]
How many is 'some'? :)

**Comment by jharvey** [comment]
via's see PC10, PC11, PC12, PD0, PD14 then on 8888 see OUT15 to OUT18 as well as IGN3 and IGN4.
