### ISSUE TITLE
test pads for CRANK and CAM

### ISSUE THREAD

**Issue by rusefi** [rusefi/hw_microRusEfi#30]
for VR crank we really need a way to hook up logic analyzer for troubleshooting. While we have tiny LED pads to solder to I would prefer a nice 2mm diameter test pad so that if needed a pin could be butt-soldered

ideally same style pad is needed on PA5 track. PA5 would be the default crank at least in the beginning (I know schematics says AnOut7 = PA6 as cam but I believe this would NOT be my first preference) ICU is still the primary mode for trigger input and ICU works on PA5 not PA6

**Comment by rusefi** [comment]
Q:  Why/when do you need pads for trigger?

A: for trigger logic troubleshooting we sometimes need to record raw signal using logic analyzer. Cranking, loss of sync - all these special cases can use logic analyzer recording of raw signal.

**Comment by 960** [comment]
What difference will these make compared to the external in connector?

You also have six 0603 footprints at the same place to solder wires.

I have tested these inputs with all kinds of signals, both hall, mcu output, VR, 1,5V battery etc..
Everything work perfect.

For the PA5 line, you will just be able to measure the same as the MCU sees?

I can add pads, I just need to know if it's really needed,

**Comment by rusefi** [comment]
Q: What difference will these make compared

A: I need processed digital crank signal not source analog VR signal

**Comment by 960** [comment]
I think I have misunderstood the question.

I will replace the led with a pad.

I still dont see why it's needed, but anyway.

Those are the MCU inputs, and I thougt you could do the exact same reading with the MCU.

**Comment by 960** [comment]
Added

**Comment by rusefi** [comment]
@960 while we can read from MCU its not comfortable.

i do not understand your goals. you are making this board hard for me to use, i am getting afraid that i do not want to be first user.

sure i would enjoy this as a product, but i am not interested in artificial hardships developing for this platform

**Comment by 960** [comment]
I have added the pads, so please just be happy with it.

**Comment by rusefi** [comment]
I see CRANK pad

I see "CAM" words but I am not sure what these are referring to, please help me find CAM pad.

![VirtualBoxVM_Tjx15fMZvt](https://user-images.githubusercontent.com/7377949/58634118-7d57a500-82b8-11e9-85a4-af4931d1559d.png)

**Comment by rusefi** [comment]
with new schematics CAM signal could be measured on the connector it looks like

no protection on CAM now?

<img width="960" alt="kicad_bFS28eisWh" src="https://user-images.githubusercontent.com/7377949/58634523-8006ca00-82b9-11e9-8474-f10585478acc.png">

**Comment by 960** [comment]
<img width="960" alt="kicad_JH0JOuUYeT" src="https://user-images.githubusercontent.com/9406140/58636495-bd3a7e80-82f0-11e9-97be-93402f02eaba.png">

**Comment by 960** [comment]
Diode added just in case

**Comment by 960** [comment]
Pads added, and can be closed
