### ISSUE TITLE
Larger T5V1/2 buffer caps

### ISSUE THREAD

**Issue by mck1117** [rusefi/hw_microRusEfi#31]
Buffer caps are currently 100nF, minimum recommended by datasheet is 400nF.  We should use 1uF or 1uF+100nF.

**Comment by 960** [comment]
<img width="960" alt="kicad_IGar3RJD2t" src="https://user-images.githubusercontent.com/9406140/58527603-963a5a80-81d3-11e9-84a5-fcb993d9ddf2.png">

**Comment by 960** [comment]
Isnt that what I have?

**Comment by mck1117** [comment]
![image](https://user-images.githubusercontent.com/568254/58527667-7598e300-8188-11e9-8d52-face87e39af6.png)

I mean for the 5 volt tracker outputs.

**Comment by mck1117** [comment]
(other supplies (5v main, 3.3v, 6v prereg) look fine)

**Comment by 960** [comment]
Ok, I just made this from the reference design.

<img width="960" alt="ApplicationFrameHost_aK3pI9PQjP" src="https://user-images.githubusercontent.com/9406140/58528351-7c4e4700-81d6-11e9-8c0a-77fcac63859b.png">

**Comment by 960** [comment]
Is it enough with larger values, or do we need larger footprints?

**Comment by rusefi** [comment]
@mck1117 ?

**Comment by mck1117** [comment]
footprints are already 0603, closing as it isn't a board issue.
