### ISSUE TITLE
Ground ignition inputs to TLE8888 + IGNEN pin

### ISSUE THREAD

**Issue by mck1117** [rusefi/hw_microRusEfi#32]
Ground unused inputs instead of leaving floating. Prevents them bouncing around on their own due to EMI.

**Comment by 960** [comment]
I can do that.

I think all have a pull-up, does that matter?

**Comment by jharvey** [comment]
I believe the stm32 has configurable pull ups and pull down. Those pull down are likely already taken care of by chibios.

**Comment by rusefi** [comment]
@jharvey i believe this ticket is about TLE8888 unused pins not stm32 unused pins

**Comment by 960** [comment]
This is done, and I think we can close.
