### ISSUE TITLE
U5 wants that 4th pin connected to GND

### ISSUE THREAD

**Issue by rusefi** [rusefi/hw_microRusEfi#36]
U5 the LM2937 schematic is missing pin4, which is connected to pin2. This causes the PCB footprint to miss the GND connection and decreases it's thermal characteristics. 

@jharvey suggests adding the pin 4 to the schematic.

**Comment by 960** [comment]
This one are solved.

Pad number 4, (now 2) are connected to GND

<img width="960" alt="kicad_BgPXXqg9lN" src="https://user-images.githubusercontent.com/9406140/58667659-ee3da200-8336-11e9-989a-bb6599004821.png">

**Comment by rusefi** [comment]
@960 was this published? do we expect schematics to show 4 pins now?

![VirtualBoxVM_qqE383gTBH](https://user-images.githubusercontent.com/7377949/58667851-2deb9600-8305-11e9-91a9-1c85760b5910.png)

**Comment by 960** [comment]
The symbol dont have pin 4

Instead of editing the symbol to be custom, I changed pad number for footprint to 2 to get ground at the Thermal pad.

**Comment by jharvey** [comment]
I agree, this one is solved.
