### ISSUE TITLE
 traces to not be under the screw heads, or under the enclosure

### ISSUE THREAD

**Issue by rusefi** [rusefi/hw_microRusEfi#39]
Can we limit to only two screws, and get some more clearance near the harness connector? That would allow traces to not be under the screw heads, or under the enclosure.

**Comment by 960** [comment]
I have rerouted the traces that got under the screw head when narrowing down edge cuts.

Under the pcb, there will be traces touching the enclosure all over it. 

For now, I would like to keep all 4 screws.

**Comment by rusefi** [comment]
there will be plastic under the pcb

**Comment by rusefi** [comment]
![VirtualBoxVM_R3jcHRi4pL](https://user-images.githubusercontent.com/7377949/58633663-1c7b9d00-82b7-11e9-8438-992f487b6b95.png)

**Comment by rusefi** [comment]
@960 says "The board doesn't touch the enclosure at top" - PCB is thinner and bolted to the bottom  leaving some small space on top everywhere.
