### ISSUE TITLE
separate constant 12v and ignition key

### ISSUE THREAD

**Issue by rusefi** [rusefi/hw_microRusEfi#5]
let's separate constant +12v from ignition ket 12v - this case we can implement tle8888 sleep delay later

**Comment by rusefi** [comment]
Poke @dron0gus

**Comment by rusefi** [comment]
![image001](https://user-images.githubusercontent.com/7377949/57902160-017c4800-7836-11e9-82de-f6f6fcfb2a8f.jpg)

**Comment by 960** [comment]
Doing this will take away one pin, as this will be a low amp wire.
If we use one of the existing pins, we only have one pin with High amp 12v.

Please explain further what this function do, and what we need it for.

**Comment by mck1117** [comment]
Without standby power to the stm32's rtc/backup sram (via backup regulator or coil cell battery), this isn't particularly useful.  So I think for this ECU we don't worry about it, and leave the wiring as is.

**Comment by 960** [comment]
I think we can close this?

It would take one connector pin, and do nothing of use.
