### ISSUE TITLE
spell out status LED colors on PDF and BOM

### ISSUE THREAD

**Issue by rusefi** [rusefi/hw_microRusEfi#57]
PE1 is blue - communication
PE2 is red - fatal
PE3 is green - running
PE4 is orange - warning

**Comment by jharvey** [comment]
Is this OK?

PE1 is orange - warning
PE2 is blue - communication
PE3 is red - fatal
PE4 is green - running

I just changed the PE# to match the BOM which I think Matt had created. I figured changing the note was easier than changing the BOM. Let me know if this should change. I think this is now closed.

**Comment by abelom** [comment]
Any pinout would work for me, very easy yo change on my end
