### ISSUE TITLE
j1 & u3 BOM

### ISSUE THREAD

**Issue by rusefi** [rusefi/hw_microRusEfi#59]
2) I would like us to improve https://rusefi.com/docs/ibom/microRusEfi_latest.html
2a) J1 - please add part number 105133-0031 so that "part #' column is populated properly.
2b) U2 - please add part number 500762-0481 so that "part #' column is populated properly.

**Comment by jharvey** [comment]
I believe this is completed, and this should be closed, Please verify and close if it should be closed.
