### ISSUE TITLE
RN1 cleanup

### ISSUE THREAD

**Issue by rusefi** [rusefi/hw_microRusEfi#60]
please improve RN1 schematics and spell out resistor value for the status LEDs. I assume 1k or 1.5K? Please unify part number of RN1 with either U52 1K or U54 1.5K

**Comment by mck1117** [comment]
installed 1k - works fine

**Comment by jharvey** [comment]
All arrays are either RN# or CN#, and they now have BOM data in the schematic. I suggest this is closed.
