### ISSUE TITLE
LED size unification

### ISSUE THREAD

**Issue by rusefi** [rusefi/hw_microRusEfi#61]
all six LEDs should use same 0805 package

**Comment by mck1117** [comment]
agree - it's hard enough to see the polarity marks on an 0603 LED, and even harder on a 0402

**Comment by rusefi** [comment]
looks like 4 stm32 status LEDs were changed to 0805
shall we unify all 6 LEDs to same 0805 size?

**Comment by jharvey** [comment]
All LED's are 0603, same for resistors and caps.

**Comment by rusefi** [comment]
Is anyone other than myself interested in having all LEDs 0805?

**Comment by jharvey** [comment]
I don't think you really car about 0805, as you do not assemble. I think your question should be are there any assemblers who care about 0805. In your case I think you care about color and readable silk screen.
