### ISSUE TITLE
D15 and D20 are underneath the connector

### ISSUE THREAD

**Issue by mck1117** [rusefi/hw_microRusEfi#62]
It's impossible to install D15 and D20 since they're underneath the plastic part of the connector.

**Comment by rusefi** [comment]
![mre_sides](https://user-images.githubusercontent.com/7377949/60070163-a6b2f780-96e3-11e9-9cbf-844d2bec4640.jpg)

**Comment by rusefi** [comment]
proposed placement - ideally it would nice to have those a bit further apart from each other

<img width="960" alt="kicad_diodes" src="https://user-images.githubusercontent.com/7377949/60388525-e7629600-9a80-11e9-9209-95e4d822b810.png">

**Comment by rusefi** [comment]
D15 & D20 were moved on 0.2 revision
