### ISSUE TITLE
Schematic labels for ignition/high side drivers are wrong

### ISSUE THREAD

**Issue by mck1117** [rusefi/hw_microRusEfi#63]
Functionality and connector pinout are ok - the labels on the schematic sheet are wrong.  Currently the first two channels (labeled IGN_1 and IGN_2) are the voltage selectable ones, which agrees with the connector pinout.

![image](https://user-images.githubusercontent.com/568254/59842413-5e728e80-930b-11e9-9a4f-6779cb7c681f.png)

**Comment by jharvey** [comment]
Just flipped the net names around. I think this can be closed.
