### ISSUE TITLE
Add pull up/down resistors for ETB control pins

### ISSUE THREAD

**Issue by mck1117** [rusefi/hw_microRusEfi#64]
Currently, between the internal pull up/down in the TLE9201 and STM32, the H bridge goes to full power reverse when the STM32 is in reset.

1) At a minimum we need a pullup resistor on the DIS pin
2) ideally also a pull down on the PWM pin.

These will ensure that even when the STM32 hasn't set up those pins yet, the throttle won't move.

**Comment by mck1117** [comment]
Adding a bodge resistor from DIS to +3.3v on my board seems to have fixed the issue, so that may be all we need.

**Comment by rusefi** [comment]
DIS pull-up is R1
PWM pull-down is R16
