### ISSUE TITLE
branding / stamp / making silkscreen area

### ISSUE THREAD

**Issue by rusefi** [rusefi/hw_microRusEfi#68]
On Frankenso I use this while area to manually scribe individual board numbers with electric punch.

Can we please add similar area on MRE so that similar manual numbering approach would be possible?

Open question why exactly do I do that at all :)
![branding](https://user-images.githubusercontent.com/7377949/60151305-40dd7300-97aa-11e9-82e6-97f28cc3d127.jpg)

**Comment by jharvey** [comment]
I added the EFI logo as well as white strip for serial number. I think this is now a closed item.
