### ISSUE TITLE
X1 to use more common part

### ISSUE THREAD

**Issue by rusefi** [rusefi/hw_microRusEfi#83]
NX3225GD-8MHZ-STD-CRA-3 is not in stock at mouser for another month. can we please change X1 to 49SMD?
![s-l500](https://user-images.githubusercontent.com/7377949/61162104-062b4880-a4d5-11e9-88f9-e8a47fc624b8.jpg)

**Comment by jharvey** [comment]
I believe this has been resolved in R0.3 and can be closed.
