### ISSUE TITLE
VDD BOOT0 usability

### ISSUE THREAD

**Issue by rusefi** [rusefi/hw_microRusEfi#86]
We still do not have https://github.com/rusefi/rusefi/issues/809 and I assume that even once we have it sometimes things would not go well, so

We need some usability for VDD<>BOOT0 jumping. At the moment we have R26 which I assume is the default 0603 which is not very useable for jumping while rebooting.

We need an SMD jumper header so that a jumper could be put to connect VDD with BOOT0 if desired

**Comment by Abricosvw** [comment]
i think best approach is not exposed pns for jumper but a touch button (not toggle button)

**Comment by rusefi** [comment]
@Abricosvw  Omron Electronics Inc-EMC Div B3U-1000P for $1.50 is too much money!

There must be something similar waaaay cheaper on eBay. Overall I like the push button idea!

**Comment by rusefi** [comment]
I like https://www.ebay.ca/itm/100PCS-3-4-2mm-Mini-Tact-Tactile-Push-Button-Switch-SMD-2Pin/232305685293

**Comment by jharvey** [comment]
What is the digikey equiv to add to the BOM?

**Comment by rusefi** [comment]
I believe the button is a bit larger than the current footprint. Can we expand by 1mm?

See image

![mre_button](https://user-images.githubusercontent.com/7377949/62827280-0e40db80-bb9a-11e9-904f-bb1cc5f9b3cb.jpg)

**Comment by jharvey** [comment]
See if this one fits better. Also this is really close, did you verify you had 100% scale? It is common that printers will print 98% scale, which can bugger things like this. I often have to print at 102% scale to get closer to the 100% scale in the real world.

**Comment by rusefi** [comment]
Looks good now!
