### ISSUE TITLE
C39 silkscreen is not clear

### ISSUE THREAD

**Issue by rusefi** [rusefi/hw_microRusEfi#89]
C39 is one of the capacitors where polarity matters, current silkscreen is unclear

**Comment by jharvey** [comment]
C39 the dark band goes closer to the screw. This is important, as flipped wrong = explosion.

**Comment by jharvey** [comment]
Silk screen has been updated to make this more clear. I believe this is closed.

**Comment by rusefi** [comment]
![image](https://user-images.githubusercontent.com/7377949/62827169-2a437d80-bb98-11e9-89e1-359880429f77.png)
