### ISSUE TITLE
Cut hardware from vref analog

### ISSUE THREAD

**Issue by mck1117** [rusefi/hw_microRusEfi#9]
The vref signal doesn't need its second series resistor R142, pulldown R143, or protection diode D14.  If these became necessary, we've already blown up the rest of the board.

**Comment by rusefi** [comment]
@mck1117 is this still an issue in your opinion?

**Comment by 960** [comment]
What voltage should be at Vref?

Doesnt it need the voltage divider R142, R143 ?

Diode are removed

**Comment by rusefi** [comment]
This implementation of VRef would be invisible for software since we feed the output into MCU vref input pin

**Comment by rusefi** [comment]
Do we need R44? Do we need R99?

**Comment by mck1117** [comment]
R44/99 are OK to leave, and initial request is now resolved. Closed!
