### ISSUE TITLE
test pads on both sides - maybe just silkscreen?

### ISSUE THREAD

**Issue by rusefi** [rusefi/hw_microRusEfi#92]
At the moment we have sweet GND and 5v test pads on the front.

Technically +12 is available on the front on Q1 and C2 and etc but there is no way to know it. Maybe some silkscreen indicating the safest spot to touch +12? Maybe a pad next to Q1 or else?

On the back we technically have GND, 5v and 12v on the connector but all of these are pretty small and pretty tight so there is a huge risk of shortening things together.

Maybe a nicer pad next to +5v on connector on the back? Maybe silkscreen explaining that mounting bolts surrounds are GND so that mounting bolt surrounds are the official pad? Maybe even remove the sweet GND text pad and explain that bolt surrounds are GND?

Maybe a nicer pad next to 12v on the back?

**Comment by jharvey** [comment]
Oops, I forgot to tag this when I pushed. Any how, I added these test pads, and I think this is now can be considered completed.
