### ISSUE TITLE
sorta kind of backfeeding? isolation?

### ISSUE THREAD

**Issue by rusefi** [rusefi/hw_microRusEfi#93]
why did MRE 0.1 reboot on me while cranking? Do we have anything preventing backfeeding? isolation?

**Comment by rusefi** [comment]
@mck1117 says
"re: low voltage dropouts, I removed r21, and now my board works down to 4.9 volts
it used to die at 7.9"

**Comment by rusefi** [comment]
@jharvey let's remove R21?

@mck1117 says " with that resistor removed, it survived a (logged) minimum voltage of 7.6 volts"

![image](https://user-images.githubusercontent.com/7377949/62336552-c4237000-b49e-11e9-987a-a211cadcd1d9.png)

**Comment by jharvey** [comment]
I think R21 is valid, it's just in the wrong place on the schematic. See R107 from the reference TBOARD schematic. Notice it's on the battery side not the key side of the filtering.

**Comment by rusefi** [comment]
![TBoard_Wake_Key_schematci](https://user-images.githubusercontent.com/7377949/62369313-3fb40a00-b4fd-11e9-86fb-7f41fbdb0774.PNG)

**Comment by rusefi** [comment]
We will see how it goes with 0.3 I guess
