### ISSUE TITLE
Rn2 rn3 rn4 rn13 wrong part number?

### ISSUE THREAD

**Issue by rusefi** [rusefi/hw_microRusEfi#94]
![1564178042914](https://user-images.githubusercontent.com/7377949/61985028-30046500-afd5-11e9-91bc-0d97aaf6c503.JPEG)

**Comment by rusefi** [comment]
@mck1117 says it should be YC164-JR-0710KL‎

**Comment by jharvey** [comment]
I just updated BOM, I believe this is now closed.
