### ISSUE TITLE
MRE#2 has paid the ultimate price.

### ISSUE THREAD

**Issue by rusefi** [rusefi/hw_microRusEfi#97]
Around 9pm this Thursday microRusEfi number two has paid the ultimate price 7 minutes into real vehicle testing. Let's never forget microRusEfi number two and the two issues it might have revealed.

**Comment by rusefi** [comment]
Would like this opportunity to clarify that a jumper wires was connector to GND of MRE and DMM was hooked to that jumper wire with alligator clip. There was no dragging of probes on the PCB during this event.

**Comment by rusefi** [comment]
With #95 and #96 tests passing it's still a mystery what has killed TLE8888

**Comment by jharvey** [comment]
This is obsolete, suggest closing this issue
